# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           _site
destination:      _gh-pages
host:             0.0.0.0
port:             6001
url:              http://iguntur.info/
encoding:         UTF-8
